return {
--  {
--   "mason-org/mason.nvim",
--    config = function()
--      require("mason").setup()
--    end
--  },
--  {
--    "mason-org/mason-lspconfig.nvim",
--    config = function()
--      require("mason-lspconfig").setup({
--        ensure_installed = {
--          "lua_ls",
--          "yamlls",
--          "bashls",
--          "dockerls",
--          "terraformls",
--          "docker_compose_language_service",
--          "pylsp",
--          "puppet"
--        }
--
--      })
--    end
--  },
--  {
--    "neovim/nvim-lspconfig",
--    config = function()
--      local lspconfig = require("lspconfig")
--      lspconfig.lua_ls.setup({})
--      lspconfig.yamlls.setup({})
--      lspconfig.bashls.setup({})
--      lspconfig.terraformls.setup({})
--      lspconfig.dockerls.setup({})
--      lspconfig.docker_compose_language_service.setup({})
--      lspconfig.pylsp.setup({})
--      lspconfig.puppet.setup({})
--
--      vim.keymap.set('n', 'K', vim.lsp.buf.hover, {})
--      vim.keymap.set('n', 'gd', vim.lsp.buf.definition, {})
--      vim.keymap.set({'n', 'v'},'<leader>ca', vim.lsp.buf.code_action, {})
--    end
--  }
}
