# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Which is equivalent to

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill$python\
\n$character"""

[directory]
truncation_length = 4
truncate_to_repo = true

[character]
success_symbol = '[ ->](bold green) '
error_symbol = '[ ->](bold red) '
vimcmd_symbol = "[ ->](bold green)"

[python]
format = '(\([$virtualenv]($style)\) )'
style = "bold red"
detect_extensions = []

[fill]
symbol = ' '
