# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Which is equivalent to

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill$python$aws$time\
\n$character"""

[directory]
truncation_length = 4
truncate_to_repo = true

[character]
success_symbol = '[ ->](bold green) '
error_symbol = '[ ->](bold red) '
vimcmd_symbol = "[ ->](bold green)"

[python]
format = '(\([$virtualenv]($style)\) )'
style = "bold red"
detect_extensions = []

[aws]
format = '(\([$profile]($style)\) )'
style = "bold yellow"

[fill]
symbol = ' '

[time]
disabled = false
time_format = "%R"
utc_time_offset = "local"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'
